[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zeroxamm_one = "BwYSdX5KxrcJzxcBhJ3zSveeJ1Cae9AgN8BDLHvY6E3v"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
