[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zeroxcounter = "44pReZEfppDqb1nspgSs7wizn8DkqTdEMKKijj6iCBaV"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
