[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zeroxpda_calculator = "Ek9j58LBsfzzeQ79uTnp2PJ2iobxtzoB89VybvgfJXPT"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
