[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zeroxescrow_o1 = "CLTjXNTG8Ph9m3kiAD948sjXNhGoRMuRCA9DtJ28tBBU"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
